# Generated by Django 4.0.2 on 2022-04-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_playlist_source'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Playlist',
            new_name='PlaylistModel',
        ),
    ]
