# Generated by Django 4.0.2 on 2022-04-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_rename_playlist_playlistmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistmodel',
            options={'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlists'},
        ),
    ]
