# Generated by Django 4.0.2 on 2022-05-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_playlistmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
